### ISSUE TITLE
Connection to database

### ISSUE THREAD

**Issue by Okjonas** [hold17/dist-hangman#1]
Vi vil gerne gemme highscore.

**Comment by awo-dev** [comment]
Probably not wanted for this project

**Comment by awo-dev** [comment]
Or a simple database?

**Comment by awo-dev** [comment]
Maybe use https://github.com/hold12/JDBC_lib for custom mysql database instead - a bit easier

**Comment by twast92** [comment]
Using Hibernate and JPA to get around writing actual SQL statements
